final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'price': 300.45,
    'imageUrl': 'assets/images/shoes.jpg',
    'company': 'NIKE',
    'size': [8, 9, 10, 11],
  },
  {
    'id': '1',
    'title': 'Men\'s Nike Shoes',
    'price': 300,
    'imageUrl': 'assets/images/shoes.jpg',
    'company': 'NIKE',
    'size': [8, 9, 10, 11],
  },
  {
    'id': '2',
    'title': 'Men\'s Nike Shoes',
    'price': 300,
    'imageUrl': 'assets/images/shoes.jpg',
    'company': 'NIKE',
    'size': [8, 9, 10, 11],
  },
  {
    'id': '3',
    'title': 'Men\'s Nike Shoes',
    'price': 300,
    'imageUrl': 'assets/images/shoes.jpg',
    'company': 'NIKE',
    'size': [8, 9, 10, 11],
  },
  {
    'id': '4',
    'title': 'Men\'s Nike Shoes',
    'price': 300,
    'imageUrl': 'assets/images/shoes.jpg',
    'company': 'NIKE',
    'size': [8, 9, 10, 11],
  },
  {
    'id': '5',
    'title': 'Men\'s Nike Shoes',
    'price': 300,
    'imageUrl': 'assets/images/shoes.jpg',
    'company': 'NIKE',
    'size': [8, 9, 10, 11],
  },
];
